sonar.projectName=CourtFlow - Lozas deportivas
sonar.sources=app,scripts
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=app/static/favicon.svg
sonar.coverage.exclusions=app/static/**,scripts/**
sonar.qualitygate.wait=true
